### ISSUE TITLE
[Bug for Laravel Intelephense]: Curly Braces Spacer throws exception

### ISSUE THREAD

**Issue by AamirSohailKmAs** [porifa/vscode-laraphense#42]
### Bug description

When we add curly braces at the start of an empty line we get the exception in the log,

### Plugin version

1.24.0

### Operating system

MacOS

### Steps to reproduce

Add curly braces at the starting position of an empty line

### Relevant log output

rejected promise not handled within 1 second: Error: Illegal argument: character must be non-negative
extensionHostProcess.js:108
stack trace: Error: Illegal argument: character must be non-negative
    at $ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:1101)
    at new r (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:4279)
    at r.translate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:4902)
    at /Users/aamir/.vscode/extensions/porifa.laravel-intelephense-1.24.0/dist/extension.js:1:205312
    at Array.forEach (<anonymous>)
    at Function.curlyBracesSpacer (/Users/aamir/.vscode/extensions/porifa.laravel-intelephense-1.24.0/dist/extension.js:1:205191)
    at r.value (/Users/aamir/.vscode/extensions/porifa.laravel-intelephense-1.24.0/dist/extension.js:1:218780)
    at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at f.x (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1972)
    at fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2188)
    at $acceptModelChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10065)
    at t.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7983)
    at t.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7749)
    at t.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:6830)
    at t.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:5906)
    at r.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4736)
    at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
    at y.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13931)
    at r.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:30355)
    at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
    at y.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13931)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:28635)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
    at Object.callbackTrampoline (node:internal/async_hooks:130:17)

**Comment by AamirSohailKmAs** [comment]
Fixed in 1.24.1
